import municipalityData from './municipality_data.json';

export type MunicipalityId = 
  | 'abucay'
  | 'alabat'
  | 'ambulong'
  | 'aparri'
  | 'baguio'
  | 'baler_radar'
  | 'basco_radar'
  | 'borongan'
  | 'butuan'
  | 'clsu'
  | 'cabanatuan'
  | 'calapan'
  | 'calayan'
  | 'casiguran'
  | 'catarman'
  | 'catbalogan'
  | 'clark'
  | 'coron'
  | 'cotabato'
  | 'cubi_point'
  | 'cuyo'
  | 'daet'
  | 'dagupan'
  | 'dauis'
  | 'davao_city'
  | 'dipolog'
  | 'dumaguete'
  | 'el_salvador'
  | 'general_santos'
  | 'guiuan'
  | 'hinatuan'
  | 'iba'
  | 'infanta'
  | 'itbayat'
  | 'juban'
  | 'laoag'
  | 'legazpi'
  | 'maasin'
  | 'mactan'
  | 'malaybalay'
  | 'masbate'
  | 'naia'
  | 'port_area'
  | 'puerto_prinsesa'
  | 'romblon'
  | 'roxas_city'
  | 'san_jose'
  | 'sangley_point'
  | 'science_garden'
  | 'sinait'
  | 'surigao'
  | 'tacloban'
  | 'tanay'
  | 'tayabas'
  | 'tuguegarao'
  | 'virac_synop'
  | 'zamboanga';

export interface Municipality {
  id: MunicipalityId;
  color: string;
}

export const municipalities: Municipality[] = [
  { id: 'abucay', color: '#2E7D32' },
  { id: 'alabat', color: '#1976D2' },
  { id: 'ambulong', color: '#F57C00' },
  { id: 'aparri', color: '#C2185B' },
  { id: 'baguio', color: '#7B1FA2' },
  { id: 'baler_radar', color: '#00796B' },
  { id: 'basco_radar', color: '#5D4037' },
  { id: 'borongan', color: '#455A64' },
  { id: 'butuan', color: '#E64A19' },
  { id: 'clsu', color: '#0097A7' },
  { id: 'cabanatuan', color: '#388E3C' },
  { id: 'calapan', color: '#6A1B9A' },
  { id: 'calayan', color: '#AFB42B' },
  { id: 'casiguran', color: '#F57C00' },
  { id: 'catarman', color: '#C2185B' },
  { id: 'catbalogan', color: '#7B1FA2' },
  { id: 'clark', color: '#00796B' },
  { id: 'coron', color: '#5D4037' },
  { id: 'cotabato', color: '#455A64' },
  { id: 'cubi_point', color: '#E64A19' },
  { id: 'cuyo', color: '#0097A7' },
  { id: 'daet', color: '#388E3C' },
  { id: 'dagupan', color: '#6A1B9A' },
  { id: 'dauis', color: '#AFB42B' },
  { id: 'davao_city', color: '#F57C00' },
  { id: 'dipolog', color: '#C2185B' },
  { id: 'dumaguete', color: '#7B1FA2' },
  { id: 'el_salvador', color: '#00796B' },
  { id: 'general_santos', color: '#5D4037' },
  { id: 'guiuan', color: '#455A64' },
  { id: 'hinatuan', color: '#E64A19' },
  { id: 'iba', color: '#0097A7' },
  { id: 'infanta', color: '#388E3C' },
  { id: 'itbayat', color: '#6A1B9A' },
  { id: 'juban', color: '#AFB42B' },
  { id: 'laoag', color: '#F57C00' },
  { id: 'legazpi', color: '#C2185B' },
  { id: 'maasin', color: '#7B1FA2' },
  { id: 'mactan', color: '#00796B' },
  { id: 'malaybalay', color: '#5D4037' },
  { id: 'masbate', color: '#455A64' },
  { id: 'naia', color: '#E64A19' },
  { id: 'port_area', color: '#0097A7' },
  { id: 'puerto_prinsesa', color: '#388E3C' },
  { id: 'romblon', color: '#6A1B9A' },
  { id: 'roxas_city', color: '#AFB42B' },
  { id: 'san_jose', color: '#F57C00' },
  { id: 'sangley_point', color: '#C2185B' },
  { id: 'science_garden', color: '#7B1FA2' },
  { id: 'sinait', color: '#00796B' },
  { id: 'surigao', color: '#5D4037' },
  { id: 'tacloban', color: '#455A64' },
  { id: 'tanay', color: '#E64A19' },
  { id: 'tayabas', color: '#0097A7' },
  { id: 'tuguegarao', color: '#388E3C' },
  { id: 'virac_synop', color: '#6A1B9A' },
  { id: 'zamboanga', color: '#AFB42B' },
];

export interface YieldData {
  year: number;
  yield: number;
}

export interface MunicipalityYieldData {
  municipalityId: MunicipalityId;
  historicalData: YieldData[];
  averageYield: number;
}

// Generate real data from your trained model
// This function generates real data from your CSV files

export const generateRealYieldData = (): MunicipalityYieldData[] => {
  // Use the real data from the JSON file generated by the Python script
  return municipalityData as MunicipalityYieldData[];
};

/** @deprecated Use generateRealYieldData() instead */
export const mockYieldData: MunicipalityYieldData[] = [];
